Dim swApp As SldWorks.SldWorks
Dim swModel As ModelDoc2
Dim swModeldocext As ModelDocExtension
Dim swSktchMger As SketchManager
' Declare a variable to store the created circle
Dim circle1 As SketchSegment

Sub main()

    ' Initialize the SolidWorks application
    Set swApp = Application.SldWorks
    
    ' Create a string type variable for storing default part location
    Dim defaultTemplate As String

    ' Set the value of this string type variable to "Default part template"
    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)
    
    ' Create a new part document using the default template
    Set swModel = swApp.NewDocument(defaultTemplate, 0, 0, 0)
    
    ' Get the model document extension object
    Set swModeldocext = swModel.Extension
    
    ' Select the top plane using model document extension
    swModeldocext.SelectByID2 "Top Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault
    
    ' Get the sketch manager to create sketch routines
    Set swSktchMger = swModel.SketchManager
    
    ' Start a new sketch
    swSktchMger.InsertSketch True
    
    ' Enable AddToDB to add sketch entities directly to the SOLIDWORKS database
    swSktchMger.AddToDB = True
    
    
    
    ' Create a circle with center at (0,0,0) and a point on the circle at (0,0.5,0)
    Set circle1 = swSktchMger.CreateCircle(0, 0, 0, 0.5, 0, 0)
    
    'creating a line and a centerline without returning value
    swSktchMger.CreateLine 0, 0, 0, 0.5, 0.5, 0
    swSktchMger.CreateCenterLine 0, 0, 0, 0, 0.89, 0
    
    ' Disable AddToDB after creating sketch entities Don't know why shaded contours are removed after adding to database
    swSktchMger.AddToDB = False
    
    ' Deselect all entities after creating the sketch
    swModel.ClearSelection2 True

    ' Show top view after creating the sketch
    swModel.ShowNamedView2 "", swStandardViews_e.swTopView
    
    ' Zoom to fit the screen in the SolidWorks window
    swModel.ViewZoomtofit2
       
End Sub

